# Generated by Django 5.1.1 on 2024-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
