# Generated by Django 5.1.1 on 2024-10-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Garanty',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='tip',
            field=models.CharField(max_length=50),
        ),
    ]
